<div class="col-4">
    <ul class="cv-list">
        <li><a href="{{url('college/view', [$university->id, $name])}}" @if(($class ?? '') == 'view') class="color-C11800" @endif > @if(($class ?? '') == 'view') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif  {{$university->name_ru}}</a></li>
        <li><a href="{{url('college/achievements', [$university->id, $name])}}" @if(($class ?? '') == 'achieve') class="color-C11800" @endif  > @if(($class ?? '') == 'achieve') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Достижения</a></li>
        <li><a href="{{url('college/coop', [$university->id, $name])}}" @if(($class ?? '') == 'coop') class="color-C11800" @endif  > @if(($class ?? '') == 'coop') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Сотрудничество</a></li>
        <li><a href="{{url('college/rating', [$university->id, $name])}}" @if(($class ?? '') == 'rating') class="color-C11800" @endif  > @if(($class ?? '') == 'rating') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Рейтинг</a></li>
        <li><a href="{{url('college/discounts', [$university->id, $name])}}" @if(($class ?? '') == 'discounts') class="color-C11800" @endif  > @if(($class ?? '') == 'discounts') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Гранты / Скидки</a></li>
        <li><a href="{{url('college/edu', [$university->id, $name])}}"  @if(($class ?? '') == 'edu') class="color-C11800" @endif  > @if(($class ?? '') == 'edu') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Образовательные программы</a></li>
        <li><a href="{{url('college/docs', [$university->id, $name])}}"  @if(($class ?? '') == 'docs') class="color-C11800" @endif  > @if(($class ?? '') == 'docs') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Документы для поступления</a></li>
        <li><a href="{{url('college/contacts', [$university->id, $name])}}"  @if(($class ?? '') == 'contacts') class="color-C11800" @endif  > @if(($class ?? '') == 'contacts') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Контакты</a></li>
    </ul>
</div>
